# References
* [Go Language Documentation Page](http://golang.org/doc/)
* [Effective Go](http://golang.org/doc/effective_go.html)
* [Go Tutorial](https://tour.golang.org/)

# Packages
Every Go program is made up of packages.

Programs start running in package ``main``. The ``main()`` func will be called.

This program is using the packages with import paths ``"fmt"`` and ``"math/rand"``.

By convention, the package name is the same as the last element of the import path. For instance, the "math/rand" package comprises files that begin with the statement package ``rand`` (aka ``rand.something``).

In [1]:
// Define a package. This is where the program starts running
package main

// import some other packages.
import (
    "fmt"
    "math/rand"
)


// define main func, like C, everything starts with a main.
func main() {
    fmt.Println("My favorite number is", rand.Intn(10))
}

// in real program you don't have to call this
main()

My favorite number is 1


# Imports
This code groups the imports into a parenthesized, "factored" import statement.

You can also write multiple import statements, like:
```GO
import "fmt"
import "math"
```
But it is good style to use the factored import statement.

In [2]:
package main

import "fmt"
import "math"

func main() {
    fmt.Printf("Now you have %g problems.\n", math.Sqrt(7))
}

// in real program you don't have to call this
main()

Now you have 2.6457513110645907 problems.


# Exported names
In Go, a name is exported if it begins with a capital letter. For example, ``Pizza`` is an exported name, as is ``Pi``, which is exported from the math package.

``pizza`` and ``pi`` do not start with a capital letter, so they are not exported.

When importing a package, you can refer only to its exported names. Any "unexported" names are not accessible from outside the package.

In [3]:
// Run the code. Notice the error message.

// To fix the error, rename math.pi to math.Pi and try it again.

package main

import (
    "fmt"
    "math"
)

func main() {
    fmt.Println(math.pi)
}
main()

ERROR: repl.go:13:17: package math "math" has no symbol pi

In [4]:
// A name is exported if it begins with a capital letter.
package main

import (
    "fmt"
    "math"
)

func main() {
    fmt.Println(math.Pi)
}
main()

3.141592653589793


# Functions
A function can take zero or more arguments.

In this example, add takes two parameters of type ``int`` and return an ``int``.

Notice that the type comes after the variable name.

In [5]:
package main

import "fmt"

func add(x int, y int) int {
    return x + y
}

func main() {
    fmt.Println(add(42, 13))
}

main()

55


When two or more consecutive named function parameters share a type, you can omit the type from all but the last.

In this example, we shortened
```GO
x int, y int
```
to
```GO
x, y int
```

In [6]:
package main

import "fmt"

func add(x, y int) int {
    return x + y
}

func main() {
    fmt.Println(add(42, 13))
}
main()

55


# Multiple results
A function can return any number of results.

The ``swap`` function returns two strings.

In [7]:
package main

import "fmt"

func swap(x, y string) (string, string) {
    return y, x
}

func main() {
    a, b := swap("hello", "world")
    fmt.Println(a, b)
}
main()

world hello


# Named return values
Go's return values may be named. If so, they are treated as variables defined at the top of the function.

These names should be used to document the meaning of the return values.

A ``return`` statement without arguments returns the named return values. This is known as a "naked" return.

Naked return statements should be used only in short functions, as with the example shown here. They can harm readability in longer functions.

In [8]:
package main

import "fmt"

func split(sum int) (x, y int) {
    x = sum * 4 / 9
    y = sum - x
    return
}

func main() {
    fmt.Println(split(17))
}


If no named return value is defined and you explicitly call return, nothing is returned.

In [9]:
package main

import "fmt"

func split(sum int) {
    fmt.Println(sum)
    return
}

func main() {
    split(17)
}
main()

17


# Variables
The ``var`` statement declares a list of variables; as in function argument lists, the type is last.

A ``var`` statement can be at package or function level. We see both in this example.

The default value for any numeric type will be 0. For boolean values the default is false and for strings it will be an empty string. While the Go programming language does have a type of nil , a string cannot be of this type.

In [10]:
package main

import "fmt"

var c, python, java bool

func main() {
    var i int
    fmt.Println(i, c, python, java)
}
main()

0 false false false


# Variables with initializers
A ``var`` declaration can include initializers, one per variable.

If an initializer is present, the type can be omitted; the variable will take the type of the initializer.

In [11]:
package main

import "fmt"

var i, j int = 1, 2

func main() {
    var c, python, java = true, false, "no!"
    fmt.Println(i, j, c, python, java)
}
main()

1 2 true false no!


# Short variable declarations
Inside a function (only. available inside a func), the ``:=`` short assignment statement can be used in place of a ``var`` declaration with implicit type.

Outside a function, every statement begins with a keyword (``var``, ``func``, and so on) and so the ``:=`` construct is not available.

In [12]:
package main

import "fmt"

func main() {
    var i, j int = 1, 2
    k := 3
    c, python, java := true, false, "no!"

    fmt.Println(i, j, k, c, python, java)
}


# Basic types
Go's basic types are
```Go
bool

string

int  int8  int16  int32  int64
uint uint8 uint16 uint32 uint64 uintptr

byte // alias for uint8

rune // alias for int32
     // represents a Unicode code point

float32 float64

complex64 complex128
```
The example shows variables of several types, and also that variable declarations may be "factored" into blocks, as with import statements.

The ``int``, ``uint``, and ``uintptr`` types are usually 32 bits wide on 32-bit systems and 64 bits wide on 64-bit systems. When you need an integer value you should use int unless you have a specific reason to use a sized or unsigned integer type.

In [13]:
package main

import (
    "fmt"
    "math/cmplx"
)

var (
    ToBe   bool       = false
    // Regarding why this is legit:
    //https://stackoverflow.com/questions/26833421/how-does-1-64-1-work
    MaxInt uint64     = 1<<64 - 1
    
    //MaxInt uint64     = 1<<64
    //this will not be okay, because uint64 can't hold this value
    z      complex128 = cmplx.Sqrt(-5 + 12i)
)

func main() {
    fmt.Printf("Type: %T Value: %v\n", ToBe, ToBe)
    fmt.Printf("Type: %T Value: %v\n", MaxInt, MaxInt)
    fmt.Printf("Type: %T Value: %v\n", z, z)
}
main()

Type: bool Value: false
Type: uint64 Value: 18446744073709551615
Type: complex128 Value: (2+3i)


# Zero values

Variables declared without an explicit initial value are given their zero value.

The zero value is:

``0`` for numeric types,

``false`` for the boolean type, and

``""`` (the empty string) for strings.


In [14]:
package main

import "fmt"

func main() {
    var i int
    var f float64
    var b bool
    var s string
    fmt.Printf("%v %v %v %q\n", i, f, b, s)
}
main()

0 0 false ""


# Type conversions
The expression ``T(v)`` converts the value ``v`` to the type ``T``.

Some numeric conversions:
```
var i int = 42
var f float64 = float64(i)
var u uint = uint(f)
```
Or, put more simply:
```
i := 42
f := float64(i)
u := uint(f)
```
Unlike in C, in Go assignment between items of different type **requires an explicit conversion**. Try removing the float64 or uint conversions in the example and see what happens.

In [15]:
package main

import (
    "fmt"
    "math"
)

func main() {
    var x, y int = 3, 4
    var f float64 = math.Sqrt(float64(x*x + y*y))
    var z uint = uint(f)
    fmt.Println(x, y, z)
}
main()

3 4 5


In [16]:
package main

import (
    "fmt"
    "math"
)

func main() {
    var x, y int = 3, 4
    var f float64 = math.Sqrt(float64(x*x + y*y))
    var z uint = f
    fmt.Println(x, y, z)
}
main()

ERROR: repl.go:11:9: incompatible types in assignment: uint = float64

# Type inference
When declaring a variable **without specifying an explicit type** (either by using the ``:=`` syntax or var ``=`` expression syntax), **the variable's type is inferred** from the value on the right hand side.

When the right hand side of the declaration is typed, the new variable is of that same type:
```
var i int
j := i // j is an int
```
But when the right hand side contains an untyped numeric constant, the new variable may be an ``int``, ``float64``, or ``complex128`` depending on the precision of the constant:
```
i := 42           // int
f := 3.142        // float64
g := 0.867 + 0.5i // complex128
```


In [17]:
package main

import "fmt"

func main() {
    v := 42 // change me!
    fmt.Printf("v is of type %T\n", v)
}
main()

v is of type int


In [18]:
package main

import "fmt"

func main() {
    v := 42.213213 // change me!
    fmt.Printf("v is of type %T\n", v)
}
main()

v is of type float64


In [19]:
package main

import "fmt"

func main() {
    v := 2 + 3i // change me!
    fmt.Printf("v is of type %T\n", v)
}
main()

v is of type complex128


# Constants
Constants are **declared like variables, but with the const keyword**.

Constants can be character, string, boolean, or numeric values.

Constants **cannot be declared using the := syntax**.

In [20]:
package main

import "fmt"

const Pi = 3.14
const Pi2 float64 = 3.14

func main() {
    const World = "世界"
    fmt.Println("Hello", World)
    fmt.Println("Happy", Pi, "Day")

    const Truth = true
    fmt.Println("Go rules?", Truth)
}
main()

Hello 世界
Happy 3.14 Day
Go rules? true


# Numeric Constants
Numeric constants are high-precision values.

An untyped constant takes the type needed by its context.

Printing ``needInt(Big)`` will cause an error bcs converting 1 << 100 to int will result in an overflow.

(An ``int`` can store at maximum a 64-bit integer, and sometimes less.)

In [21]:
package main

import "fmt"

const (
    // Create a huge number by shifting a 1 bit left 100 places.
    // In other words, the binary number that is 1 followed by 100 zeroes.
    Big = 1 << 100
    // Shift it right again 99 places, so we end up with 1<<1, or 2.
    Small = Big >> 99
    
    // you dont want to do this just bcs it will restrict the value of const
    // Big int = 1 << 63
)

func needInt(x int) int { return x*10 + 1 }
func needFloat(x float64) float64 {
    return x * 0.1
}

func main() {
    fmt.Println(needInt(Small))
    fmt.Println(needFloat(Small))
    fmt.Println(needFloat(Big))
    
    // this will raise an error when converted to int.
    //fmt.Println(needInt(Big))
}
main()

21
0.2
0


# For
Go has only one looping construct, the ``for`` loop.

The basic ``for`` loop has three components separated by semicolons:

    the init statement: executed before the first iteration
    the condition expression: evaluated before every iteration
    the post statement: executed at the end of every iteration
    The init statement will often be a short variable declaration, and the variables declared there are visible only in the scope of the for statement.

The loop will stop iterating once the boolean condition evaluates to ``false``.

Note: Unlike other languages like C, Java, or JavaScript there are **no parentheses** surrounding the three components of the for statement and the braces ``{ }`` are always required.

In [26]:
package main

import "fmt"

func main() {
    sum := 0
    for i := 0; i < 10; i++ {
        sum += i
    }
    
    for i := 0; i < 10; i++ {
        sum += i
    }
    fmt.Println(sum)
}
main()

ERROR: repl.go:11:12: expected ')', found ':=' (and 1 more errors)

# For continued
The init and post statements are optional.

In [23]:
package main

import "fmt"

func main() {
    sum := 1
    for ; sum < 1000; {
        sum += sum
    }
    fmt.Println(sum)
}
main()

1024


# For is Go's "while"
At that point you can drop the semicolons: C's ``while`` is spelled ``for`` in Go.

In [24]:
package main

import "fmt"

func main() {
    sum := 1
    for sum < 1000 {
    sum += sum
    }
    fmt.Println(sum)
}
main()

1024


# Forever
If you omit the loop condition it loops forever, so an infinite loop is compactly expressed.

In [25]:
package main

func main() {
    //for {
    //}
}
main()

# If
Go's if statements are like its for loops; the expression **need not be surrounded by parentheses** ``( )`` but the braces ``{ }`` are required.

In [28]:
package main

import (
    "fmt"
    "math"
)

func sqrt(x float64) string {
    if x < 0 {
        return sqrt(-x) + "i"
    }
    return fmt.Sprint(math.Sqrt(x))
}

func main() {
    fmt.Println(sqrt(2), sqrt(-4))
}
main()

1.4142135623730951 2i


# If with a short statement
Like for, the if statement **can start with a short statement to execute before the condition**.

Variables declared by the statement are only in scope until the end of the if.

(Try using v in the last return statement.)

In [31]:
package main

import (
    "fmt"
    "math"
)

func pow(x, n, lim float64) float64 {
    if v := math.Pow(x, n); v < lim {
        return v
    }
    return lim
}

func main() {
    fmt.Println(
        pow(3, 2, 10),
        pow(3, 3, 20),
    )
}
main()

9 20


# If and else
Variables declared inside an if short statement **are also available inside any of the else** blocks.

(Both calls to pow return their results before the call to fmt.Println in main begins.)

In [34]:
package main

import (
    "fmt"
    "math"
)

func pow(x, n, lim float64) float64 {
    if v := math.Pow(x, n); v < lim {
        return v
    } else {
        fmt.Printf("%g >= %g\n", v, lim)
    }
    // can't use v here, though
    return lim
}

func main() {
    fmt.Println(
        pow(3, 2, 10),
        pow(3, 3, 20),
    )
}
main()

27 >= 20
9 20


# Switch
A ``switch`` statement is a shorter way to write a sequence of ``if - else`` statements. It **runs the first case** whose value is equal to the condition expression. It also supports a short statement before it begins

Go's switch is like the one in C, C++, Java, JavaScript, and PHP, except that Go only runs the selected case, not all the cases that follow. In effect, the ``break`` statement that is needed at the end of each case in those languages **is provided automatically in Go**. Another important difference is that **Go's switch cases need not be constants, and the values involved need not be integers**.

In [38]:
package main

import (
    "fmt"
    "runtime"
)

func main() {
    fmt.Print("Go runs on ")
    switch os := runtime.GOOS; os {
    case "darwin":
        fmt.Println("OS X.")
    case "linux":
        fmt.Println("Linux.")
    default:
        // freebsd, openbsd,
        // plan9, windows...
        fmt.Printf("%s.\n", os)
    }
}
main()

Go runs on OS X.


## Switch evaluation order
Switch cases evaluate cases from top to bottom, stopping when a case succeeds.

(For example,
```GO
switch i {
case 0:
case f():
}
```
does not call f if i==0.)

In [41]:
package main

import (
    "fmt"
    "time"
)

func main() {
    fmt.Println("When's Saturday?")
    today := time.Now().Weekday()
    switch time.Saturday {
    case today + 0:
    fmt.Println("Today.")
    case today + 1:
    fmt.Println("Tomorrow.")
    case today + 2:
    fmt.Println("In two days.")
    case today + 3:
    fmt.Println("In three days.")
    case today + 4:
    fmt.Println("In four days.")
    default:
    fmt.Println("Too far away.")
    }
}
main()

When's Saturday?
Today.


# Switch with no condition

Switch without a condition is the same as ``switch true``.

This construct can be a clean way to write long if-then-else chains. It's basically trying to look for a ``true`` in the conditions below.

In [43]:
package main

import (
    "fmt"
    "time"
)

func main() {
    t := time.Now()
    switch {
    case t.Hour() < 12:
        fmt.Println("Good morning!")
    case t.Hour() < 17:
        fmt.Println("Good afternoon.")
    default:
        fmt.Println("Good evening.")
    }
}
main()

Good afternoon.


# Defer
A ``defer`` statement defers the execution of a function **until the surrounding function returns (aka parent func)**.

The deferred call's **arguments are evaluated immediately**, but the function call **is not executed until the surrounding function returns**.

``defer`` is often used where e.g. ``ensure`` and ``finally`` would be used in other languages.

In Go language, multiple defer statements are allowed in the same program and **they are executed in LIFO**.

In [46]:
package main

import "fmt"

func main() {
    defer fmt.Println("defer until main returned")

    fmt.Println("hello")
    fmt.Println("main returned")
}
main()


hello
main returned
defer until main returned


# Stacking defers
Deferred function calls are pushed onto a stack. When a function returns, its deferred calls are executed in last-in-first-out order.

To learn more about defer statements read [this blog post](https://blog.golang.org/defer-panic-and-recover).

In [49]:
package main

import "fmt"

func main() {
    fmt.Println("counting")
    
    // for loop is not a function
    for i := 0; i < 10; i++ {
        defer fmt.Println(i)
    }

    fmt.Println("done")
}
main()

counting
done
9
8
7
6
5
4
3
2
1
0


# Pointers
Go has pointers. A pointer holds the memory address of a value.

The type ``*T`` is a pointer to a T value. Its zero value is ``nil``.

The ``&`` operator generates a pointer to its operand.
```GO
var p *int
i := 42
p = &i
```

The ``*`` operator denotes the pointer's underlying value.
```
fmt.Println(*p) // read i through the pointer p
*p = 21         // set i through the pointer p
```

This is known as "dereferencing" or "indirecting".

Unlike C, Go **has no pointer arithmetic**.

In [2]:
package main

import "fmt"

func main() {
    i, j := 42, 2701

    p := &i         // point to i
    fmt.Println(*p) // read i through the pointer
    *p = 21         // set i through the pointer
    fmt.Println(i)  // see the new value of i

    p = &j         // point to j
    *p = *p / 37   // divide j through the pointer
    fmt.Println(j) // see the new value of j
}
main()

42
21
73


# Structs
A ``struct`` is a collection of fields.

Struct fields are accessed using a dot ``.``.

In [9]:
package main

import "fmt"

type Vertex struct {
    X int
    Y int
}

func main() {
    a := Vertex{1, 2}
    fmt.Println(a.X, a.Y)
    
    fmt.Println(Vertex{1,3})
    
    b := Vertex{}
    b.X = 4
    b.Y = 4
    fmt.Println(b)
}
main()

1 2
{1 3}
{4 4}


# Pointers to structs
Struct fields can be accessed through a struct pointer.

To access the field ``X`` of a struct when we have the struct pointer p we could write ``(*p).X``. However, that notation is cumbersome, so the language permits us instead to write just ``p.X``, **without the explicit dereference**. Note here that you can **only assume implicit defreference when accessing a field**.

In [15]:
package main

import "fmt"

type Vertex struct {
    X int
    Y int
}

func main() {
    v := Vertex{1, 2}
    p := &v
    p.X = 1e9
    fmt.Println(v)
    
    var p2 *Vertex = &v
    p2.X = 10
    p2.Y = 10
    fmt.Println(v)
    fmt.Println(p)
    fmt.Println(*p)
    
}
main()

{1000000000 2}
{10 10}
&{10 10}
{10 10}


# Struct Literals
A struct literal denotes a newly allocated struct value by listing the values of its fields.

You can list just a subset of fields by using the ``Name:`` syntax. (And the order of named fields is irrelevant.)

The special prefix `&` returns a pointer to the struct value.

In [17]:
package main

import "fmt"

type Vertex struct {
    X, Y int
}

var (
    v1 = Vertex{1, 2}  // has type Vertex
    v2 = Vertex{X: 1}  // Y:0 is implicit
    v3 = Vertex{}      // X:0 and Y:0
    p  = &Vertex{1, 2} // has type *Vertex
)

func main() {
    fmt.Println(v1, p, v2, v3)
}
main()

{1 2} &{1 2} {1 0} {0 0}


# Arrays
The type ``[n]T`` is an array of ``n`` values of type `T`. Its length `n` is part of its type ([4]int and [5]int are distinct, incompatible types)

The expression
```
var a [10]int
```
declares a variable a as an array of ten integers. Arrays do not need to be initialized explicitly; the zero value of an array is a ready-to-use array whose elements are themselves zeroed (like `c` in the example below).

An array's length is part of its type, so **arrays cannot be resized**. This seems limiting, but don't worry; Go provides a convenient way of working with arrays. Like C, you **cannot use a variable to set the array size**.

The in-memory representation of [4]int is just four integer values laid out sequentially:

![arr_mem](https://blog.golang.org/slices-intro/slice-array.png)

Go's arrays are values. **An array variable denotes the entire array**; it is **not a pointer to the first array element** (as would be the case in C). This means that **when you assign or pass around an array value you will make a copy of its contents**. (To avoid the copy you could pass a pointer to the array, but then that's a pointer to an array, not an array.) One way to think about arrays is as a sort of struct but with indexed rather than named fields: a fixed-size composite value.

An array literal can be specified like so:
```
b := [2]string{"Penn", "Teller"}
```
Or, you can have the compiler count the array elements for you:
```
b := [...]string{"Penn", "Teller"}
```
In both cases, the type of b is [2]string.

In [50]:
package main

import "fmt"

func main() {
    var a [2]string
    a[0] = "Hello"
    a[1] = "World"
    fmt.Println(a[0], a[1])
    fmt.Println(a)

    primes := [6]int{2, 3, 5, 7, 11, 13}
    fmt.Println(primes)
    
    //b := 5
    //var c [b]string //this is not ok
    
    var c [3]int
    fmt.Println(c)
    
    d := [...]string{"Penn", "Teller"}
    fmt.Println(d)
}
main()

Hello World
[Hello World]
[2 3 5 7 11 13]
[0 0 0]
[Penn Teller]


# Slices
An array has a fixed size. A slice, on the other hand, is a dynamically-sized, flexible view into the elements of an array. In practice, slices are much more common than arrays.

The type ``[]T`` is a slice with elements of type ``T``.

A slice is formed by specifying two indices, a low and high bound, separated by a colon:
```go
a[low : high]
```
This selects a half-open range which includes the first element, but excludes the last one.

The following expression creates a slice which includes elements 1 through 3 of ``a``:
```go
a[1:4]
```
# Slices are like references to arrays
**A slice does not store any data**, it just describes a section of an underlying array.

Changing the elements of a slice modifies the corresponding elements of its underlying array.

Other slices that share the same underlying array will see those changes.

In [26]:
package main

import "fmt"

func main() {
    primes := [6]int{2, 3, 5, 7, 11, 13}

    var s []int = primes[1:4]
    fmt.Println(s)
    
    // there's a limit there.
    a := primes[2:5]
    
    // you can't do this, but bcs you know the array size, so this is ok
    //a := primes[3:9]
    fmt.Println(a)

}
main()

[3 5 7]
[5 7 11]


In [28]:
package main

import "fmt"

func main() {
names := [4]string{
    "John",
    "Paul",
    "George",
    "Ringo",
    }
    fmt.Println(names)

    a := names[0:2]
    b := names[1:3]
    fmt.Println(a, b)

    b[0] = "XXX"
    fmt.Println(a, b)
    fmt.Println(names)
}
main()

[John Paul George Ringo]
[John Paul] [Paul George]
[John XXX] [XXX George]
[John XXX George Ringo]


# Slice literals
A slice literal is like an array literal without the length.

This is an array literal:
```
[3]bool{true, true, false}
```
And this creates the same array as above, then builds a slice that references it:
```
// this returns a slice, rather than an array. It creates an array and then returns a slice pointing to it.
[]bool{true, true, false}
```

In [38]:
package main

import "fmt"

func main() {
    q := []int{2, 3, 5, 7, 11, 13}
    q1 := q[2:4]
    fmt.Println(q)

    r := []bool{true, false, true, true, false, true}
    fmt.Println(r)

    s := []struct {
        i int
        b bool
    }{
        {2, true},
        {3, false},
        {5, true},
        {7, true},
        {11, false},
        {13, true},
    }
    fmt.Println(s)
}
main()

[2 3 5 7 11 13]
[true false true true false true]
[{2 true} {3 false} {5 true} {7 true} {11 false} {13 true}]


# Slice defaults
When slicing, you may omit the high or low bounds to use their defaults instead.

The default is zero for the low bound and the length of the slice for the high bound.

For the array
```go
var a [10]int
```
these slice expressions are equivalent:
```go
a[0:10]
a[:10]
a[0:]
a[:]
```

In [39]:
package main

import "fmt"

func main() {
    s := []int{2, 3, 5, 7, 11, 13}

    s = s[1:4]
    fmt.Println(s)

    s = s[:2]
    fmt.Println(s)

    s = s[1:]
    fmt.Println(s)
}
main()

[3 5 7]
[3 5]
[5]


# Slice length and capacity
A slice has both **a length** and **a capacity**.

The **length** of a slice is **the number of elements it contains**.

The **capacity** of a slice is the number of elements in the underlying array, counting from the first element in the slice.

The length and capacity of a slice ``s`` can be obtained using the expressions ``len(s)`` and ``cap(s)``.

You can extend a slice's length by re-slicing it, provided it has sufficient capacity. Try changing one of the slice operations in the example program to extend it beyond its capacity and see what happens.

In [41]:
package main

import "fmt"

func main() {
    s := []int{2, 3, 5, 7, 11, 13}
    printSlice(s)

    // Slice the slice to give it zero length.
    s = s[:0]
    printSlice(s)

    // Extend its length.
    s = s[:4]
    printSlice(s)

    // Drop its first two values.
    s = s[2:]
    printSlice(s)
}

func printSlice(s []int) {
    fmt.Printf("len=%d cap=%d %v\n", len(s), cap(s), s)
}
main()

len=6 cap=6 [2 3 5 7 11 13]
len=0 cap=6 []
len=4 cap=6 [2 3 5 7]
len=2 cap=4 [5 7]


# Nil slices
The **zero value of a slice** is ``nil``.

A **nil slice has a length and capacity of 0** and has no underlying array.

In [43]:
package main

import "fmt"

func main() {
    var s []int
    fmt.Println(s, len(s), cap(s))
    if s == nil {
        fmt.Println("nil!")
    }
}
main()

[] 0 0
nil!


# Creating a slice with make
Slices can be created with the built-in ``make`` function; this is how you create dynamically-sized arrays.

The make function allocates a zeroed array and returns a slice that refers to that array:
```
a := make([]int, 5)  // len(a)=5
```
To specify a capacity, pass a third argument to make:
```
b := make([]int, 0, 5) // len(b)=0, cap(b)=5

b = b[:cap(b)] // len(b)=5, cap(b)=5
b = b[1:]      // len(b)=4, cap(b)=4
```

In [45]:
package main

import "fmt"

func main() {
    a := make([]int, 5)
    printSlice("a", a)

    b := make([]int, 0, 5)
    printSlice("b", b)

    c := b[:2]
    printSlice("c", c)
    
    // see this is possible bcs c is a slice,you can extend it. It's operating on the underlying array
    d := c[2:5]
    printSlice("d", d)
}

func printSlice(s string, x []int) {
    fmt.Printf("%s len=%d cap=%d %v\n",
    s, len(x), cap(x), x)
}
main()

a len=5 cap=5 [0 0 0 0 0]
b len=0 cap=5 []
c len=2 cap=5 [0 0]
d len=3 cap=3 [0 0 0]


# Slice internals
A slice is a descriptor of an array segment. It consists of a pointer to the array, the length of the segment, and its capacity (the maximum length of the segment).

![slice_internal](https://blog.golang.org/slices-intro/slice-struct.png)

A slice by make([]byte, 5), is structured like this:

![slice_5](https://blog.golang.org/slices-intro/slice-1.png)

The length is the number of elements referred to by the slice. The capacity is the number of elements in the underlying array (**beginning at the element referred to by the slice pointer**). The distinction between length and capacity will be made clear as we walk through the next few examples.

As we slice s, observe the changes in the slice data structure and their relation to the underlying array:

s = s[2:4]

![s_24](https://blog.golang.org/slices-intro/slice-2.png)

**Slicing does not copy the slice's data**. It creates a new slice value that points to the original array. This makes slice operations as efficient as manipulating array indices. Therefore, **modifying the elements (not the slice itself) of a re-slice modifies the elements of the original slice**:
```go
d := []byte{'r', 'o', 'a', 'd'}
e := d[2:]
// e == []byte{'a', 'd'}
e[1] = 'm'
// e == []byte{'a', 'm'}
// d == []byte{'r', 'o', 'a', 'm'}
```
Earlier we sliced s to a length shorter than its capacity. We can grow s to its capacity by slicing it again:
```go
s = s[:cap(s)]
```
![cap_s](https://blog.golang.org/slices-intro/slice-3.png)
A slice cannot be grown beyond its capacity. Attempting to do so will cause a runtime panic, just as when indexing outside the bounds of a slice or array. Similarly, **slices cannot be re-sliced below zero to access earlier elements in the array**.

# Slices of slices
Slices can contain any type, including other slices.

In [51]:
package main

import (
    "fmt"
    "strings"
)

func main() {
    // Create a tic-tac-toe board.
    board := [][]string{
        []string{"_", "_", "_"},
        []string{"_", "_", "_"},
        []string{"_", "_", "_"},
    }

    // The players take turns.
    board[0][0] = "X"
    board[2][2] = "O"
    board[1][2] = "X"
    board[1][0] = "O"
    board[0][2] = "X"

    for i := 0; i < len(board); i++ {
        fmt.Printf("%s\n", strings.Join(board[i], " "))
    }
}
main()

X _ X
O _ X
_ _ O


# Growing Slice
To increase the capacity of a slice one must create a new, larger slice and copy the contents of the original slice into it. This technique is how dynamic array implementations from other languages work behind the scenes. The next example doubles the capacity of s by making a new slice, t, copying the contents of s into t, and then assigning the slice value t to s:
```go
s = make([]byte, 5)
t := make([]byte, len(s), (cap(s)+1)*2) // +1 in case cap(s) == 0
for i := range s {
        t[i] = s[i]
}
s = t
```
The looping piece of this common operation is made easier by the built-in copy function. As the name suggests, copy copies data from a source slice to a destination slice. It returns the number of elements copied.
```go
func copy(dst, src []T) int
```
The copy function supports copying between slices of different lengths (it will copy only up to the smaller number of elements). In addition, copy can handle source and destination slices that share the same underlying array, handling overlapping slices correctly.

Using copy, we can simplify the code snippet above:

```go
t := make([]byte, len(s), (cap(s)+1)*2)
copy(t, s)
s = t
```

In [61]:
package main

import (
    "fmt"
    "strings"
)

func main() {
    // one way of growing a slice into double the size
    s := []byte{1, 2, 3, 4, 5}
    printSlice("s", s)
    t := make([]byte, len(s), (cap(s)+1)*2) // +1 in case cap(s) == 0
    printSlice("t", t)
    for i := range s {
        t[i] = s[i]
    }
    s = t
    printSlice("s", s)
    
    // a simplified way of growing a slice into double the size
    t1 := make([]byte, len(s), (cap(s)+1)*2)
    copy(t, s)
    s1 := t
    printSlice("s1", s1)
}

func printSlice(name string, x []byte) {
    fmt.Printf("%s len=%d cap=%d %v\n",
    name, len(x), cap(x), x)
}
main()

s len=5 cap=5 [1 2 3 4 5]
t len=5 cap=12 [0 0 0 0 0]
s len=5 cap=12 [1 2 3 4 5]
s1 len=5 cap=12 [1 2 3 4 5]


## Append
A common operation is to append data to the end of a slice. This function appends byte elements to a slice of bytes, growing the slice if necessary, and returns the updated slice value:
```go
func AppendByte(slice []byte, data ...byte) []byte {
    m := len(slice)
    n := m + len(data)
    if n > cap(slice) { // if necessary, reallocate
        // allocate double what's needed, for future growth.
        newSlice := make([]byte, (n+1)*2)
        copy(newSlice, slice)
        slice = newSlice
    }
    slice = slice[0:n]
    copy(slice[m:n], data)
    return slice
}
```
One could use AppendByte like this:
```go
p := []byte{2, 3, 5}
p = AppendByte(p, 7, 11, 13)
// p == []byte{2, 3, 5, 7, 11, 13}
```
Functions like ``AppendByte`` are useful because they offer complete control over the way the slice is grown. Depending on the characteristics of the program, it may be desirable to allocate in smaller or larger chunks, or to put a ceiling on the size of a reallocation.

But most programs don't need complete control, so Go provides a built-in ``append`` function that's good for most purposes; it has the signature
```go
func append(s []T, x ...T) []T
```
The append function appends the elements x to the end of the slice s, and grows the slice if a greater capacity is needed. **The new array size (aka new cap) is determined by the built-in func**.
```go
a := make([]int, 1)
// a == []int{0}
a = append(a, 1, 2, 3)
// a == []int{0, 1, 2, 3}
```
To append one slice to another, use ... to expand the second argument to a list of arguments.
```go
a := []string{"John", "Paul"}
b := []string{"George", "Ringo", "Pete"}
a = append(a, b...) // equivalent to "append(a, b[0], b[1], b[2])"
// a == []string{"John", "Paul", "George", "Ringo", "Pete"}
```
Since the zero value of a slice (nil) acts like a zero-length slice, you can declare a slice variable and then append to it in a loop:
```go
// Filter returns a new slice holding only
// the elements of s that satisfy fn()
func Filter(s []int, fn func(int) bool) []int {
    var p []int // == nil
    for _, v := range s {
        if fn(v) {
            p = append(p, v)
        }
    }
    return p
}
```

In [67]:
package main

import (
    "fmt"
    "strings"
)

func main() {
    // append to a slice using naive approach
    fmt.Println("Use Naive")
    p := []byte{2, 3, 5}
    printSlice("p",p)
    p = AppendByte(p, 7, 11, 13)
    printSlice("p",p)
    
    // append to a slice using more advanced
    fmt.Println("Use Built-in Append")
    p := []byte{2, 3, 5}
    printSlice("p",p)
    p = append(p, 7, 11)
    printSlice("p",p)
    
    // append a slice to a slice 
    fmt.Println("Append Slice to Slice")
    a := []byte{1,4}
    p := []byte{2, 3, 5}
    printSlice("p",p)
    p = append(p, a...)
    printSlice("p",p)
}

// a naive way of creating append, also double the array size (after_append_size + 1) * 2
func AppendByte(slice []byte, data ...byte) []byte {
    m := len(slice)
    n := m + len(data)
    if n > cap(slice) { // if necessary, reallocate
        // allocate double what's needed, for future growth.
        newSlice := make([]byte, (n+1)*2)
        copy(newSlice, slice)
        slice = newSlice
    }
    slice = slice[0:n]
    copy(slice[m:n], data)
    return slice
}

func printSlice(name string, x []byte) {
    fmt.Printf("%s len=%d cap=%d %v\n",
    name, len(x), cap(x), x)
}
main()

Use Naive
p len=3 cap=3 [2 3 5]
p len=6 cap=14 [2 3 5 7 11 13]
Use Built-in Append
p len=3 cap=3 [2 3 5]
p len=5 cap=6 [2 3 5 7 11]
Append Slice to Slice
p len=3 cap=3 [2 3 5]
p len=5 cap=6 [2 3 5 1 4]


# A possible "gotcha"
As mentioned earlier, re-slicing a slice doesn't make a copy of the underlying array. **The full array will be kept in memory until it is no longer referenced**. Occasionally this can cause the program to hold all the data in memory when only a small piece of it is needed.

To fix this problem one can copy the interesting data using the ``copy`` function to a new slice before returning it. 
```go
func copy(dst, src []Type) int
```
Copy will **copy the acutal data**. The source and destination may overlap. Copy returns the number of elements copied, which will be the minimum of len(src) and len(dst).

In [78]:
package main

import (
    "fmt"
    "strings"
)

func main(){
    var large = []int{1,2,3,4,5,6,7,8}
    var a = make([]int,3)
    n := copy(a, large)
    fmt.Println(n)
    a[1] = 100
    fmt.Println(large)
    fmt.Println(a)
}
main()

3
[1 2 3 4 5 6 7 8]
[1 100 3]


# Range
The ``range`` form of the ``for`` loop **iterates over a slice or map**.

When ranging over a slice, **two values are returned for each iteration**. The first is the index, and the second is a copy of the element at that index.

In [80]:
package main

import "fmt"

var pow = []int{1, 2, 4, 8, 16, 32, 64, 128}

func main() {
    for i, v := range pow {
        fmt.Printf("2**%d = %d\n", i, v)
    }
}
main()

2**0 = 1
2**1 = 2
2**2 = 4
2**3 = 8
2**4 = 16
2**5 = 32
2**6 = 64
2**7 = 128


# Range continued
You can skip the index or value by assigning to `_`.
```go
for i, _ := range pow
for _, value := range pow
```
If you only want the index, you can omit the second variable.
```go
for i := range pow
```
This provides a **convenient way to iterate over the slice while changing its value**:
```go
for i := range pow {
        pow[i] = 1 << uint(i) // == 2**i
}
```

In [85]:
package main

import "fmt"

func main() {
    pow := make([]int, 3)
    // use index only, such that you can change the value in the actual array.
    for i := range pow {
        pow[i] = 1 << uint(i) // == 2**i
    }
    for _, value := range pow {
        fmt.Printf("%d\n", value)
    }
}
main()

1
2
4
